title: "Bytewreaker"
tagline: "Bug Bounty & CTF Writeups"
description: "Writeups on hacking challenges, CTFs, and bug bounty adventures."

url: "https://bytewreaker.github.io"
baseurl: "/blog"

lang: en
timezone: Asia/Kolkata

author:
  name: "Bytewreaker"
  bio: "Bug bounty hunter | CTF player | Infosec enthusiast"

github:
  username: bytewreaker

comments:
  provider: false

social:
  links:
    - https://github.com/bytewreaker

theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

paginate: 5
paginate_path: /page:num/
